# This script removes every file generated by premake as well as other IDE-related files

#!/bin/bash

shopt -s globstar nullglob

for file in **/*.vcxproj **/*.vcxproj.filters **/*.vcxproj.user **/*.sln **/*.dsp **/*.dsw **/*.cbp **/*.workspace **/Makefile; do
	if [[ "$file" != external/* ]]; then
		rm -f "$file" 2>/dev/null
		relPath="${file#$PWD/}"
		echo "Deleted $relPath"
	fi
done

for dir in .vs .vscode .idea .settings .cproject .metadata; do
	for match in **/"$dir"; do
		if [[ "$match" != external/* ]] && [ -d "$match" ]; then
			rm -rf "$match" 2>/dev/null
			relPath="${match#$PWD/}"
			echo "Deleted $relPath"
		fi
	done
done

echo "Workspace reset."